// Bundles the plugin into the single `main.js` Obsidian loads. Straight from the official
// obsidian-sample-plugin, with the generated icon table pulled in as ordinary source.

import esbuild from 'esbuild';
import { builtinModules } from 'node:module';
import process from 'node:process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const production = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
		...builtinModules.map((name) => `node:${name}`),
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	minify: production,
	outfile: 'main.js',
});

if (production) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
