// Symbol id -> Lucide glyph. Obsidian ships Lucide, so these cost nothing in the bundle: the
// renderer asks Obsidian's `getIcon()` for the glyph by name.
//
// Pattern: a frozen lookup table of candidate names, tried in order. Lucide renames glyphs
// between releases and every Obsidian version pins its own, so a single hard-coded name would
// silently stop resolving; the fallbacks keep an id working across versions.

/** The id is also the search term, so name them the way people ask. */
export const SYMBOLS: Readonly<Record<string, readonly string[]>> = {
	game: ['gamepad-2', 'gamepad'],
	arcade: ['joystick'],
	rpg: ['swords'],
	trophy: ['trophy'],
	dice: ['dices', 'dice-5'],
	puzzle: ['puzzle'],
	document: ['file-text'],
	book: ['book-open'],
	school: ['graduation-cap'],
	work: ['briefcase'],
	invoice: ['receipt'],
	money: ['dollar-sign'],
	wallet: ['wallet'],
	shopping: ['shopping-cart'],
	chart: ['chart-column', 'bar-chart-3', 'bar-chart'],
	calendar: ['calendar'],
	mail: ['mail'],
	chat: ['message-circle'],
	music: ['music'],
	headphones: ['headphones'],
	podcast: ['mic'],
	movie: ['film'],
	video: ['video'],
	tv: ['tv'],
	photo: ['camera'],
	image: ['image'],
	art: ['palette'],
	design: ['pen-tool'],
	code: ['code', 'code-2'],
	terminal: ['terminal'],
	database: ['database'],
	server: ['server'],
	hardware: ['cpu'],
	bug: ['bug'],
	lab: ['flask-conical'],
	ai: ['brain'],
	bot: ['bot'],
	rocket: ['rocket'],
	tools: ['wrench'],
	package: ['package'],
	archive: ['archive'],
	download: ['download'],
	upload: ['upload'],
	cloud: ['cloud'],
	web: ['globe'],
	key: ['key'],
	private: ['lock'],
	security: ['shield'],
	phone: ['smartphone'],
	desktop: ['monitor'],
	laptop: ['laptop'],
	home: ['house', 'home'],
	person: ['user'],
	family: ['users'],
	pets: ['paw-print'],
	travel: ['plane'],
	map: ['map'],
	car: ['car'],
	fitness: ['dumbbell'],
	food: ['pizza'],
	coffee: ['coffee'],
	nature: ['leaf'],
	sun: ['sun'],
	night: ['moon'],
	favorite: ['heart'],
	star: ['star'],
	bookmark: ['bookmark'],
	flag: ['flag'],
	important: ['zap'],
	hot: ['flame'],
	magic: ['sparkles'],
	crown: ['crown'],
	gift: ['gift'],
	ghost: ['ghost'],
	skull: ['skull'],
};

/** Lucide names to try for a symbol id, or `null` for an id this build does not know. */
export function symbolGlyphs(id: string): readonly string[] | null {
	return Object.hasOwn(SYMBOLS, id) ? (SYMBOLS[id] ?? null) : null;
}
